name: TestWevebsiteDolly
favicon: null
layout_spectrum: 0.20279351714998484
typography_spectrum: 0.46033648611046374
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.7542796828784049
  lightness: 0.6591135619673878
  saturation: 0.8416946590878069
  rhythmicContrast: 0.8531742035411298
purpose: []
